export const locations = [
  {
    id: 0,
    name: 'San Francisco',
    abbreviation: 'SF',
    disease: 'Blue',
  },
  {
    id: 1,
    name: 'Chicago',
    abbreviation: 'CH',
    disease: 'Blue',
  },
  {
    id: 2,
    name: 'Toronto',
    abbreviation: 'TO',
    disease: 'Blue',
  },
  {
    id: 3,
    name: 'Atlanta',
    abbreviation: 'AT',
    disease: 'Blue',
  },
  {
    id: 4,
    name: 'New York',
    abbreviation: 'NY',
    disease: 'Blue',
  },
  {
    id: 5,
    name: 'Washington DC',
    abbreviation: 'WA',
    disease: 'Blue',
  },
  {
    id: 6,
    name: 'London',
    abbreviation: 'LO',
    disease: 'Blue',
  },
  {
    id: 7,
    name: 'Madrid',
    abbreviation: 'MA',
    disease: 'Blue',
  },
  {
    id: 8,
    name: 'Essen',
    abbreviation: 'ES',
    disease: 'Blue',
  },
  {
    id: 9,
    name: 'Paris',
    abbreviation: 'PA',
    disease: 'Blue',
  },
  {
    id: 10,
    name: 'Milan',
    abbreviation: 'MI',
    disease: 'Blue',
  },
  {
    id: 11,
    name: 'St. Petersburg',
    abbreviation: 'SP',
    disease: 'Blue',
  },
  {
    id: 12,
    name: 'Algiers',
    abbreviation: 'AL',
    disease: 'Black',
  },
  {
    id: 13,
    name: 'Cairo',
    abbreviation: 'CA',
    disease: 'Black',
  },
  {
    id: 14,
    name: 'Riyadh',
    abbreviation: 'RI',
    disease: 'Black',
  },
  {
    id: 15,
    name: 'Baghdad',
    abbreviation: 'BA',
    disease: 'Black',
  },
  {
    id: 16,
    name: 'Istanbul',
    abbreviation: 'IS',
    disease: 'Black',
  },
  {
    id: 17,
    name: 'Moscow',
    abbreviation: 'MO',
    disease: 'Black',
  },
  {
    id: 18,
    name: 'Tehran',
    abbreviation: 'TE',
    disease: 'Black',
  },
  {
    id: 19,
    name: 'Karachi',
    abbreviation: 'KA',
    disease: 'Black',
  },
  {
    id: 20,
    name: 'Delhi',
    abbreviation: 'DE',
    disease: 'Black',
  },
  {
    id: 21,
    name: 'Mumbai',
    abbreviation: 'MU',
    disease: 'Black',
  },
  {
    id: 22,
    name: 'Chennai',
    abbreviation: 'CH',
    disease: 'Black',
  },
  {
    id: 23,
    name: 'Kolkata',
    abbreviation: 'KO',
    disease: 'Black',
  },
  {
    id: 24,
    name: 'Bangkok',
    abbreviation: 'BA',
    disease: 'Red',
  },
  {
    id: 25,
    name: 'Jakarta',
    abbreviation: 'JA',
    disease: 'Red',
  },
  {
    id: 26,
    name: 'Sydney',
    abbreviation: 'SY',
    disease: 'Red',
  },
  {
    id: 27,
    name: 'Manila',
    abbreviation: 'MA',
    disease: 'Red',
  },
  {
    id: 28,
    name: 'Ho Chi Minh',
    abbreviation: 'HC',
    disease: 'Red',
  },
  {
    id: 29,
    name: 'Hong Kong',
    abbreviation: 'HK',
    disease: 'Red',
  },
  {
    id: 30,
    name: 'Shanghai',
    abbreviation: 'SH',
    disease: 'Red',
  },
  {
    id: 31,
    name: 'Beijing',
    abbreviation: 'BE',
    disease: 'Red',
  },
  {
    id: 32,
    name: 'Seoul',
    abbreviation: 'SE',
    disease: 'Red',
  },
  {
    id: 33,
    name: 'Tokyo',
    abbreviation: 'TO',
    disease: 'Red',
  },
  {
    id: 34,
    name: 'Osaka',
    abbreviation: 'OS',
    disease: 'Red',
  },
  {
    id: 35,
    name: 'Taipei',
    abbreviation: 'TA',
    disease: 'Red',
  },
  {
    id: 36,
    name: 'Los Angeles',
    abbreviation: 'LA',
    disease: 'Yellow',
  },
  {
    id: 37,
    name: 'Mexico City',
    abbreviation: 'MC',
    disease: 'Yellow',
  },
  {
    id: 38,
    name: 'Miami',
    abbreviation: 'MI',
    disease: 'Yellow',
  },
  {
    id: 39,
    name: 'Bogota',
    abbreviation: 'BO',
    disease: 'Yellow',
  },
  {
    id: 40,
    name: 'Lima',
    abbreviation: 'LI',
    disease: 'Yellow',
  },
  {
    id: 41,
    name: 'Santiago',
    abbreviation: 'SA',
    disease: 'Yellow',
  },
  {
    id: 42,
    name: 'Buenos Aires',
    abbreviation: 'BA',
    disease: 'Yellow',
  },
  {
    id: 43,
    name: 'São Paulo',
    abbreviation: 'SP',
    disease: 'Yellow',
  },
  {
    id: 44,
    name: 'Lagos',
    abbreviation: 'LA',
    disease: 'Yellow',
  },
  {
    id: 45,
    name: 'Khartoum',
    abbreviation: 'KH',
    disease: 'Yellow',
  },
  {
    id: 46,
    name: 'Johannesburg',
    abbreviation: 'JO',
    disease: 'Yellow',
  },
  {
    id: 47,
    name: 'Kinshasa',
    abbreviation: 'KI',
    disease: 'Yellow',
  },
];

export const routes = [
  ['San Francisco', 'Chicago'],
  ['San Francisco', 'Tokyo'],
  ['San Francisco', 'Manila'],
  ['San Francisco', 'Los Angeles'],
  ['Chicago', 'Atlanta'],
  ['Chicago', 'Toronto'],
  ['Chicago', 'Los Angeles'],
  ['Chicago', 'Mexico City'],
  ['Toronto', 'New York'],
  ['Toronto', 'Washington DC'],
  ['New York', 'London'],
  ['New York', 'Madrid'],
  ['New York', 'Washington DC'],
  ['Atlanta', 'Washington DC'],
  ['Atlanta', 'Miami'],
  ['Washington DC', 'Miami'],
  ['London', 'Essen'],
  ['London', 'Madrid'],
  ['London', 'Paris'],
  ['Madrid', 'Paris'],
  ['Madrid', 'Algiers'],
  ['Madrid', 'São Paulo'],
  ['Paris', 'Essen'],
  ['Paris', 'Milan'],
  ['Paris', 'Algiers'],
  ['Essen', 'Milan'],
  ['Essen', 'St. Petersburg'],
  ['St. Petersburg', 'Moscow'],
  ['St. Petersburg', 'Istanbul'],
  ['Milan', 'Istanbul'],
  ['Los Angeles', 'Sydney'],
  ['Los Angeles', 'Mexico City'],
  ['Mexico City', 'Miami'],
  ['Mexico City', 'Bogota'],
  ['Mexico City', 'Lima'],
  ['Lima', 'Santiago'],
  ['Lima', 'Bogota'],
  ['Bogota', 'Miami'],
  ['Bogota', 'Buenos Aires'],
  ['Bogota', 'São Paulo'],
  ['São Paulo', 'Buenos Aires'],
  ['São Paulo', 'Lagos'],
  ['Lagos', 'Khartoum'],
  ['Lagos', 'Kinshasa'],
  ['Kinshasa', 'Johannesburg'],
  ['Kinshasa', 'Khartoum'],
  ['Khartoum', 'Johannesburg'],
  ['Khartoum', 'Cairo'],
  ['Algiers', 'Istanbul'],
  ['Cairo', 'Algiers'],
  ['Cairo', 'Istanbul'],
  ['Cairo', 'Baghdad'],
  ['Cairo', 'Riyadh'],
  ['Istanbul', 'Moscow'],
  ['Istanbul', 'Baghdad'],
  ['Moscow', 'Tehran'],
  ['Tehran', 'Baghdad'],
  ['Tehran', 'Karachi'],
  ['Tehran', 'Delhi'],
  ['Baghdad', 'Riyadh'],
  ['Baghdad', 'Karachi'],
  ['Riyadh', 'Karachi'],
  ['Karachi', 'Delhi'],
  ['Karachi', 'Mumbai'],
  ['Delhi', 'Mumbai'],
  ['Delhi', 'Chennai'],
  ['Delhi', 'Kolkata'],
  ['Mumbai', 'Chennai'],
  ['Chennai', 'Bangkok'],
  ['Chennai', 'Jakarta'],
  ['Chennai', 'Kolkata'],
  ['Kolkata', 'Hong Kong'],
  ['Kolkata', 'Bangkok'],
  ['Jakarta', 'Sydney'],
  ['Jakarta', 'Ho Chi Minh'],
  ['Jakarta', 'Bangkok'],
  ['Bangkok', 'Ho Chi Minh'],
  ['Bangkok', 'Hong Kong'],
  ['Ho Chi Minh', 'Manila'],
  ['Ho Chi Minh', 'Hong Kong'],
  ['Manila', 'Sydney'],
  ['Manila', 'Taipei'],
  ['Manila', 'Hong Kong'],
  ['Hong Kong', 'Shanghai'],
  ['Hong Kong', 'Taipei'],
  ['Shanghai', 'Taipei'],
  ['Shanghai', 'Tokyo'],
  ['Shanghai', 'Seoul'],
  ['Shanghai', 'Beijing'],
  ['Beijing', 'Seoul'],
  ['Seoul', 'Tokyo'],
  ['Tokyo', 'Osaka'],
  ['Osaka', 'Taipei'],
];
